Repository GEOS-ESM/GEOS_OceanGridComp, pull requests merged in 2023-11, with the labels that each got.

#47 House cleaning of configurations
  .circleci/config.yml
  MOM6_GEOSPlug/mom6_app/1440x1080/MOM_input
  MOM6_GEOSPlug/mom6_app/360x210/MOM_input
  MOM6_GEOSPlug/mom6_app/360x210/MOM_override
  MOM6_GEOSPlug/mom6_app/360x210/MOM_parameter_doc.all
  MOM6_GEOSPlug/mom6_app/360x210/README.md
  MOM6_GEOSPlug/mom6_app/360x210/data_table
  MOM6_GEOSPlug/mom6_app/360x210/diag_table
  MOM6_GEOSPlug/mom6_app/360x210/input.nml
  MOM6_GEOSPlug/mom6_app/360x320/MOM_input
  MOM6_GEOSPlug/mom6_app/360x320/MOM_override
  MOM6_GEOSPlug/mom6_app/360x320/data_table
  MOM6_GEOSPlug/mom6_app/360x320/diag_table
  MOM6_GEOSPlug/mom6_app/360x320/geos/MOM_input
  MOM6_GEOSPlug/mom6_app/360x320/geos/MOM_override
  MOM6_GEOSPlug/mom6_app/360x320/geos/README.md
  MOM6_GEOSPlug/mom6_app/360x320/input.nml
  MOM6_GEOSPlug/mom6_app/360x320/soca/MOM_input
  MOM6_GEOSPlug/mom6_app/360x320/soca/MOM_override
  MOM6_GEOSPlug/mom6_app/360x320/soca/README.md
  MOM6_GEOSPlug/mom6_app/540x458/MOM_input
  MOM6_GEOSPlug/mom6_app/540x458/MOM_override
  MOM6_GEOSPlug/mom6_app/72x36/MOM_input
Labels: 0 diff structural

#49 Routine maintenance/update
  MOM6_GEOSPlug/mom6_app/540x458/MOM_override
  MOM6_GEOSPlug/mom6_app/540x458/data_table
  MOM6_GEOSPlug/mom6_cmake/CMakeLists.txt
Labels: 0 diff structural

#52 Sync Main and develop
  .circleci/config.yml
  MIT_GEOS5PlugMod/instructions/checkout_geosmitv11.1.1.txt
  MIT_GEOS5PlugMod/instructions/checkout_geosmitv11.1.txt
  MIT_GEOS5PlugMod/instructions/example_scripts/AGCM.rc
  MIT_GEOS5PlugMod/instructions/example_scripts/HISTORY.rc
  MIT_GEOS5PlugMod/instructions/example_scripts/gcm_run.j
  MIT_GEOS5PlugMod/instructions/example_scripts/geosmitenv_v11.1.sh
  MOM6_GEOSPlug/mom6_app/1440x1080/MOM_input
  MOM6_GEOSPlug/mom6_app/360x210/MOM_input
  MOM6_GEOSPlug/mom6_app/360x210/MOM_override
  MOM6_GEOSPlug/mom6_app/360x210/MOM_parameter_doc.all
  MOM6_GEOSPlug/mom6_app/360x210/README.md
  MOM6_GEOSPlug/mom6_app/360x210/data_table
  MOM6_GEOSPlug/mom6_app/360x210/diag_table
  MOM6_GEOSPlug/mom6_app/360x210/input.nml
  MOM6_GEOSPlug/mom6_app/360x320/MOM_input
  MOM6_GEOSPlug/mom6_app/360x320/MOM_override
  MOM6_GEOSPlug/mom6_app/360x320/data_table
  MOM6_GEOSPlug/mom6_app/360x320/diag_table
  MOM6_GEOSPlug/mom6_app/360x320/geos/MOM_input
  MOM6_GEOSPlug/mom6_app/360x320/geos/MOM_override
  MOM6_GEOSPlug/mom6_app/360x320/geos/README.md
  MOM6_GEOSPlug/mom6_app/360x320/input.nml
  MOM6_GEOSPlug/mom6_app/360x320/soca/MOM_input
  MOM6_GEOSPlug/mom6_app/360x320/soca/MOM_override
  MOM6_GEOSPlug/mom6_app/360x320/soca/README.md
  MOM6_GEOSPlug/mom6_app/540x458/MOM_input
  MOM6_GEOSPlug/mom6_app/540x458/MOM_override
  MOM6_GEOSPlug/mom6_app/540x458/data_table
  MOM6_GEOSPlug/mom6_app/540x458/input.nml
  MOM6_GEOSPlug/mom6_app/72x36/MOM_input
  MOM6_GEOSPlug/mom6_cmake/CMakeLists.txt
Labels: 0 diff trivial

#55 GitFlow: Merge develop into main
  MOM6_GEOSPlug/mom6_app/1440x1080/MOM_override
  MOM6_GEOSPlug/mom6_app/72x36/MOM_override
Labels: 0 diff
