Repository GEOS-ESM/GEOS_OceanGridComp, pull requests merged in 2023-05, with the labels that each got.

#26 Maintenance/Update MOM6
  MOM6_GEOSPlug/mom6_cmake/CMakeLists.txt
Labels: 0 diff, enhancement

#27 Feature/atrayano/mit config gmready
  MIT_GEOS5PlugMod/MIT_GEOS5PlugMod.F90
  MIT_GEOS5PlugMod/configs/c12_cs32_01/code/CPP_EEOPTIONS.h
  MIT_GEOS5PlugMod/configs/c12_cs32_01/code/CPP_OPTIONS.h
  MIT_GEOS5PlugMod/configs/c12_cs32_01/code/SEAICE_LAYERS.h
  MIT_GEOS5PlugMod/configs/c12_cs32_01/code/SEAICE_OPTIONS.h
  MIT_GEOS5PlugMod/configs/c12_cs32_01/code/packages.conf
  MIT_GEOS5PlugMod/configs/c12_cs32_01/code/seaice_model.F
  MIT_GEOS5PlugMod/configs/c90_llc90_02/code/CPP_EEOPTIONS.h
  MIT_GEOS5PlugMod/configs/c90_llc90_02/code/CPP_OPTIONS.h
  MIT_GEOS5PlugMod/configs/c90_llc90_02/code/CTRL_FIELDS.h
  MIT_GEOS5PlugMod/configs/c90_llc90_02/code/DIAG_OPTIONS.h
  MIT_GEOS5PlugMod/configs/c90_llc90_02/code/GMREDI_OPTIONS.h
  MIT_GEOS5PlugMod/configs/c90_llc90_02/code/SEAICE_OPTIONS.h
  MIT_GEOS5PlugMod/configs/c90_llc90_02/code/SIZE.h
  MIT_GEOS5PlugMod/configs/c90_llc90_02/code/gmredi_calc_psi_b.F
  MIT_GEOS5PlugMod/configs/c90_llc90_02/code/gmredi_calc_tensor.F
  MIT_GEOS5PlugMod/configs/c90_llc90_02/code/ini_mixing.F
  MIT_GEOS5PlugMod/configs/c90_llc90_02/code/mom_calc_visc.F
  MIT_GEOS5PlugMod/configs/c90_llc90_02/code/packages.conf
  MIT_GEOS5PlugMod/configs/c90_llc90_02/input/data
  MIT_GEOS5PlugMod/configs/c90_llc90_02/input/data.exch2
  MIT_GEOS5PlugMod/configs/c90_llc90_02/input/data.ggl90
  MIT_GEOS5PlugMod/configs/c90_llc90_02/input/data.gmredi
  MIT_GEOS5PlugMod/configs/c90_llc90_02/input/data.salt_plume
  MIT_GEOS5PlugMod/configs/c90_llc90_02/input/data.seaice
  MIT_GEOS5PlugMod/configs/c90_llc90_02/input/eedata
Labels: 0 diff

#28 Sync main with develop
  MIT_GEOS5PlugMod/MIT_GEOS5PlugMod.F90
  MIT_GEOS5PlugMod/configs/c12_cs32_01/code/CPP_EEOPTIONS.h
  MIT_GEOS5PlugMod/configs/c12_cs32_01/code/CPP_OPTIONS.h
  MIT_GEOS5PlugMod/configs/c12_cs32_01/code/SEAICE_LAYERS.h
  MIT_GEOS5PlugMod/configs/c12_cs32_01/code/SEAICE_OPTIONS.h
  MIT_GEOS5PlugMod/configs/c12_cs32_01/code/packages.conf
  MIT_GEOS5PlugMod/configs/c12_cs32_01/code/seaice_model.F
  MIT_GEOS5PlugMod/configs/c90_llc90_02/code/CPP_EEOPTIONS.h
  MIT_GEOS5PlugMod/configs/c90_llc90_02/code/CPP_OPTIONS.h
  MIT_GEOS5PlugMod/configs/c90_llc90_02/code/CTRL_FIELDS.h
  MIT_GEOS5PlugMod/configs/c90_llc90_02/code/DIAG_OPTIONS.h
  MIT_GEOS5PlugMod/configs/c90_llc90_02/code/GMREDI_OPTIONS.h
  MIT_GEOS5PlugMod/configs/c90_llc90_02/code/SEAICE_OPTIONS.h
  MIT_GEOS5PlugMod/configs/c90_llc90_02/code/SIZE.h
  MIT_GEOS5PlugMod/configs/c90_llc90_02/code/gmredi_calc_psi_b.F
  MIT_GEOS5PlugMod/configs/c90_llc90_02/code/gmredi_calc_tensor.F
  MIT_GEOS5PlugMod/configs/c90_llc90_02/code/ini_mixing.F
  MIT_GEOS5PlugMod/configs/c90_llc90_02/code/mom_calc_visc.F
  MIT_GEOS5PlugMod/configs/c90_llc90_02/code/packages.conf
  MIT_GEOS5PlugMod/configs/c90_llc90_02/input/data
  MIT_GEOS5PlugMod/configs/c90_llc90_02/input/data.exch2
  MIT_GEOS5PlugMod/configs/c90_llc90_02/input/data.ggl90
  MIT_GEOS5PlugMod/configs/c90_llc90_02/input/data.gmredi
  MIT_GEOS5PlugMod/configs/c90_llc90_02/input/data.salt_plume
  MIT_GEOS5PlugMod/configs/c90_llc90_02/input/data.seaice
  MIT_GEOS5PlugMod/configs/c90_llc90_02/input/eedata
  MOM6_GEOSPlug/mom6_cmake/CMakeLists.txt
Labels: 0 diff structural, enhancement
