Repository GEOS-ESM/GEOS_OceanGridComp, pull requests merged in 2023-08, with the labels that each got.

#36 HFREEZE option added for 1/3 degree resolution (540x458)
  MOM6_GEOSPlug/mom6_app/540x458/MOM_override
Labels: 0 diff trivial

#39 Sync develop and main
  .circleci/config.yml
  MOM6_GEOSPlug/mom6_app/540x458/MOM_override
Labels: 0 diff

#38 Maintenance/Update MOM6
  MOM6_GEOSPlug/mom6_cmake/CMakeLists.txt
Labels: 0 diff

#40 Re-sync main and develop
  MOM6_GEOSPlug/mom6_cmake/CMakeLists.txt
Labels: 0 diff

#41 Updated coarse configuration
  MOM6_GEOSPlug/mom6_app/540x458/MOM_channels_global_tx06v1
  MOM6_GEOSPlug/mom6_app/540x458/MOM_input
  MOM6_GEOSPlug/mom6_app/540x458/MOM_override
  MOM6_GEOSPlug/mom6_app/540x458/MOM_parameter_doc.all
Labels: 0 diff, enhancement
