Repository GEOS-ESM/GEOS_OceanGridComp, pull requests merged in 2025-07, with the labels that each got.

#102 v2: Update MOM6 to mom-ocean/mom6 as of 2025-Jun-02
  MOM6_GEOSPlug/mom6_cmake/CMakeLists.txt
Labels: 0 diff

#96 rotate Agrid currents to zonal and meridional directions for release V2
  MOM6_GEOSPlug/MOM6_GEOSPlug.F90
Labels: Non 0-diff, bugfix

#95 rotate Agrid currents to zonal and meridional directions
  MOM6_GEOSPlug/MOM6_GEOSPlug.F90
Labels: Non 0-diff, bugfix

#103 v3: Merge develop into main for v3 release.
  MOM6_GEOSPlug/MOM6_GEOSPlug.F90
  MOM6_GEOSPlug/mom6_cmake/CMakeLists.txt
Labels: Non 0-diff
